name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    format-and-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v3

            - uses: denoland/setup-deno@main
              with:
                  deno-version: v1.x

            - name: Check Format
              run: npm run fmt -- --check

            - name: Lint
              run: npm run lint
